import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/Header'
import { Aside } from '@/components/Aside'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'VSCODE-BRUNO FRÖHLICH',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen flex justify-center items-center bg-gradient-to-r from-cyan-400 to-blue-700 overflow-hidden">
          <div className="w-[75%] h-[85%] flex flex-col bg-gray-700 rounded">
            <Header />
            <div className="flex h-full">
              <Aside />
              <div className="w-full h-full bg-gray-700 p-8 overflow-auto custom-scrollbar">
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
